architect:
  - l3r8yJ
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/git-notifier/version.rb
    git add lib/gitnotifier/version.rb
    git commit -m "version set to ${tag}"
    gem build git-notifier.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    gem install bundler
    bundle update
    bundle install
    bundle exec rake
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
